### ISSUE TITLE
Default JSON output has .xml file extension instead

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/pyrophen#6]
## Description
I built the .jar file, and then I ran:

`java -jar target/pyrophen.jar --hpo ~/Desktop/hp.obo`

The generated file was: `hpo_fhir.xml`

However, the format of this file is JSON (as expected).

**Comment by ShahimEssaid** [comment]
I created #7

**Comment by joeflack4** [comment]
Nice!
